### PR TITLE
only run app caching for events that have cf_app_id

### PR DESCRIPTION
**Pull request by ablease**
The [request](https://github.com/cloudfoundry-community/go-cfclient/blob/master/apps.go#L59) sent by `go-cfclient` to get a list of app details is a very DB heavy operation on the Cloud Controller and it does not scale well with the number of apps running in CF.

This PR intends to make the caching logic disabled if the list of events the user subscribed for does not contain events that needs to be decorated with app details.

events that have cf_app_id:

* HttpStart
* HttpStop
* HttpStartStop # collected by us
* ContainerMetric # collected by us
* LogMessage

events that do not:

* ValueMetric
* CounterEvent
* Error

Even if `inline-relations-depth=2` were removed from go-cfclient firehose-to-syslog would still send a request for every 50 apps in the result set.

Until a better solution is found this change would allow us to run firehose-to-syslog with the non-cf_app_id events configured.

Signed-off-by: Bence Monus <bmonus@pivotal.io>

### CODE REVIEW

**Comment by ablease** [comment]
closed until fixing PR

**Comment by shinji62** [comment]
Why don't you just provides an user we just the doppler persmission ??

**Comment by cromega** [comment]
@shinji62 with a non-admin user the request sent by cfclient will fail. It will show up as potentially suspicious activity in the cloud controller logs. With this change the entire caching mechanism wouldn't start for logs that don't need it.

Do you have a suggestion for changing our implementation?

**Comment by shinji62** [comment]
It's fine.
Please squash your commit I will merge after.

**Comment by cromega** [comment]
@shinji62 done.

**Pull request merged**
