### PR TITLE
Refactor boltdb caching to improve perf and fix critical bugs

### PR DESCRIPTION
**Pull request by chenziliang**
There are 5 critical concerns in the current boltdb cache implementation:
1) caching.Caching interface are not ideal and there seems having quite some confusion, duplication,  inefficiency and very hard to handle error
- confusion: GetAppByGuid vs GetAppInfo vs GetAppInfoCache
- duplication: GetAppByGuid vs GetAppInfo vs GetAppInfoCache, end user actually only needs one and all of the implementation details can hide from end user like getting from cache or not.
- inefficiency: returning App struct by value instead of by point *App or []*App
- error handling: the interfaces have no error returned at all (almost swallowed by implementation)

2) Race condition
- There is race condition between CachingBolt.Close and background goroutine which refreshes the cache by fetching PCF server for app info or MISSING_APP_BUCKET manipulating background goroutine

3) Crashing
- MISSING_APP_BUCKET is cleaned up periodically. When checking if the app is already missing, after getting the bucket by ` b := tx.Bucket([]byte(MISSING_APP_BUCKET))` , we must check the nullness of b since the bucket may not exist any more hence nil bucket.

4) Performance
- App lookup by GUID is not efficient since we need consult boltdb every time which is expensive. Where there are lots of apps and large volume of events, the cost adds up.

5) No unit testing
- No unit test caused the above critical bugs un-discovered

This PR resolves all of the above critical bugs, clean up the caching interfaces and improve the performance for app lookup by GUID for happy cases, but still keep the features parity as original implementation.

The code coverage for new code in this PR is 88.7 %.
All existing unit tests have passed.
Performance improvement is 20X in my testing on my MacBook for happy cases

### CODE REVIEW

**Comment by chenziliang** [comment]
Code coverage:

screen shot 2017-07-24 at 12 11 32 am

**Comment by chenziliang** [comment]
Unit tests

```
kchen@splunk firehose-to-syslog (develop)$make test                                                                                                                                                        
ginkgo -r -v .
Running Suite: Caching Suite
============================
Random Seed: 1500880373
Will run 6 of 6 specs

Caching Get app good case 
  Have 10 apps
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:150
•
------------------------------
Caching Get app good case 
  Expect app
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:159
•
------------------------------
Caching Get app bad case 
  Expect no app
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:174
•
------------------------------
Caching Cache invalidation 
  Expect new app
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:196
•
------------------------------
Caching NewCachingBolt error 
  Expect error
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:208
[2017-07-24 00:13:02.969372776 -0700 PDT] Exception occurred! Message: Fail to open boltdb:  Details: open /not-exists-1500880382968632043/boltdb: no such file or directory
•
------------------------------
Caching Load from existing boltdb 
  Expect 10 apps from existing boltdb
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:237
•
Ran 6 of 6 Specs in 10.055 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: EventRouting Suite
=================================
Random Seed: 1500880373
Will run 5 of 5 specs

Events called with a empty list 
  should return a hash of only the default event
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventRouting_test.go:28
•
------------------------------
Events called with a list of bogus event names 
  should err out
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventRouting_test.go:35
•
------------------------------
Events called with a list of real event names 
  should return a hash of events
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventRouting_test.go:46
•
------------------------------
Events called after 10 events have been routed 
  should return a total of 10
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventRouting_test.go:59
•
------------------------------
Events GetListAuthorizedEventEvents 
  should return right list of authorized events
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventRouting_test.go:66
•
Ran 5 of 5 Specs in 0.000 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: Events Suite
===========================
Random Seed: 1500880373
Will run 3 of 3 specs

Events given a envelope 
  should give us what we want
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/events/events_test.go:32
•
------------------------------
Events given metadata 
  Should give us the right metadata
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/events/events_test.go:41
•
------------------------------
Events given Application Metadata 
  Should give us the right Application metadata
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/events/events_test.go:67
•
Ran 3 of 3 Specs in 0.000 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: Extra Fields Suite
=================================
Random Seed: 1500880373
Will run 6 of 6 specs

Extra Fields ParseExtraFields called with a empty string 
  should return a empty hash
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:22
•
------------------------------
Extra Fields ParseExtraFields called with extra events 
  should return a hash with the events we want
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:30
•
------------------------------
Extra Fields ParseExtraFields called with extra events with weird whitespace 
  should return a hash with the events we want
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:38
•
------------------------------
Extra Fields ParseExtraFields called with extra events with to many values to a kv pair 
  should return a error
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:46
•
------------------------------
Extra Fields FieldExist Called with existing value 
  should return true
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:55
•
------------------------------
Extra Fields FieldExist Called with existing value 
  should return false
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/extrafields/extrafields_suite_test.go:64
•
Ran 6 of 6 Specs in 0.000 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: Logging Suite
============================
Random Seed: 1500880373
Will run 3 of 3 specs

Logging SetupLogging called with a Text formatter 
  should set the logging formatter as TextFormatter
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/logging/logging_suite_test.go:21
•
------------------------------
Logging SetupLogging called with a JSON formatter 
  should set the logging formatter as JSONFormatter
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/logging/logging_suite_test.go:28
•
------------------------------
Logging SetupLogging called with a nil formatter 
  should set the logging formatter as JSONFormatter
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/logging/logging_suite_test.go:35
•
Ran 3 of 3 Specs in 0.000 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: UaaTokenRefresher Suite
======================================
Random Seed: 1500880373
Will run 1 of 1 specs

UAATokenRefresher 
  fetches a token from the UAA
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/uaatokenrefresher/uaa_token_refresher_test.go:38
•
Ran 1 of 1 Specs in 0.001 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Running Suite: Utils Suite
==========================
Random Seed: 1500880373
Will run 3 of 3 specs

Testing Utils packages UUID Formated Called with proper UUID 
  Should return formated String
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/utils/utils_test.go:17
•
------------------------------
Testing Utils packages Concat String  Called with String Map 
  Should return Concat string
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/utils/utils_test.go:25
•
------------------------------
Testing Utils packages Concat String  Called with String Map 
  Should return Proper string
  /Users/kchen/gocode/src/github.com/cloudfoundry-community/firehose-to-syslog/utils/utils_test.go:28
•
Ran 3 of 3 Specs in 0.000 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 7 suites in 14.652717185s
Test Suite Passed

```

**Comment by shinji62** [comment]
Nice PR,  let me some time to ingest.

Thanks

**Comment by chenziliang** [comment]
@shinji62 Thank you for taking time in reviewing.

**Comment by chenziliang** [comment]
@shinji62 May I ask if there is ETA for this get reviewed ? I am asking this because splunk-firehose-nozzle is currently depending on this changes. 

Appreciate for your time again!

**Comment by shinji62** [comment]
Have to revert.
Please fix the issue below and resubmit a PR.
```
------------------------------
Caching Get app bad case 
  Expect no app
  /tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:174

• Failure [1.016 seconds]
Caching
/tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:239
  Get app bad case
  /tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:175
    Expect no app [It]
    /tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:174

    Expected error:
        <*errors.errorString | 0xc420257c70>: {
            s: "App was missed and ignored",
        }
        App was missed and ignored
    not to have occurred

    /tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_test.go:172
------------------------------

```

**Comment by shinji62** [comment]
@chenziliang Don't get me wrong I revert the PR because the test do not pass.  If you make the test pass again, ust submit a new PR event including the change in #155 .

**Comment by chenziliang** [comment]
@shinji62 Got it. I got it passed in 155

**Pull request merged**
