### PR TITLE
Add LOG_MESSAGE_LIMIT setting

### LINKED ISSUE #111: Need feature to split message size sent to syslog
With recent Pivotal Cloud Foundry releases, the message size went from 4k to 60k. Unfortunately our syslog server have a hard-coded size setting at 10k, therefore we can't consume messages larger than ~9.5k.
We need the ability to specify a maximum message size and have the firehose-to-syslog application manually split the message and send those chunk to the syslog server. Without this feature, our syslog server just truncate and discard the content exceeding its message size.

Something like SYSLOG_MAXMSGSIZE setting.

### PR DESCRIPTION
**Pull request by deejross**
This is to resolve #111 

Message length is determined only by the message itself, without the additional metadata. Default is 0, which is disabled. If set higher, messages longer than this setting will be split into chunks, each containing the original metadata, with an added field `seq_num`, which is a zero-based index to describe the order of the chunk.

### CODE REVIEW

**Comment by shinji62** [comment]
Let me think about this PR.
As I already say I don't want to much logic into this nozzle.

Thanks for the PR, I will check it later.

**Comment by deejross** [comment]
Sure thing, and thank you. I tried to keep it as simple as I could. I felt that only checking the message length itself, rather than trying to calculate the message length plus all the metadata was a good compromise. So if the syslog server's limit is 10k, setting LOG_MESSAGE_LIMIT to 9k would give plenty of room for the added metadata without going over 10k, and keeping the additional computational costs to a minimum. If not using the new setting at all, the new `if` statement should be cheap enough to not introduce any noticeable slowdowns.

**Comment by jmk4791** [comment]
[DEV LOGS.txt](https://github.com/cloudfoundry-community/firehose-to-syslog/files/528814/DEV.LOGS.txt)
[Splunk.txt](https://github.com/cloudfoundry-community/firehose-to-syslog/files/528815/Splunk.txt)

Actually we are having some issue related to logs, because we are facing truncating issue in logs on SPLUNK or SYSLOG server eventhough we deployed firehose app (Current Repo) on PCF 

I have attached the original JSON file that DEV is trying to post the message to SPLUNK or SYSLOG and we could see the logs are tuncating in SPLUNK

SYSLOG message size limit : 8k  (SYSLOG Server) and we specified log_message_limit as 10 (environment variable) in firehose app 

I have attached both logs what we are trying to send and receive

Send: DEVLOGS file
Receive: Splunk (on SYSLOG)

Can you please anyone to assist on this issue?

**Comment by jmk4791** [comment]
Can anyone assist on me for truncation issue

**Pull request closed without merging**
