### PR TITLE
Move events to proprer file

### PR DESCRIPTION
**Pull request by shinji62**
Move events related code to proper file, will be easier and cleaner to change it after wards

### CODE REVIEW

**Comment by shinji62** [comment]
I added a check on the possible event, will display rejected event and fallback to LogMessage if all of specifed events are wrong

**Comment by simonjohansson** [comment]
Lovely!

I wonder if there is any way of using authorizeEvents in the list in the kingpin documentation in main.go.
That way we only have to update in one place should events be added/removed.

**Comment by shinji62** [comment]
Please merge this one I will look into it tomorrow ;) end of the day for me lol japan time

Envoyé de mon iPhone

**Comment by simonjohansson** [comment]
Ok, will merge. :)

**Pull request merged**
