### PR TITLE
Support authentication via UAA client.

### PR DESCRIPTION
**Pull request by jmcarp**
Depends on
https://github.com/cloudfoundry-community/go-cfclient/pull/36.

### CODE REVIEW

**Comment by shinji62** [comment]
Ok, I think you didn't test your PR. 
I just compile and try to saw that your code was not working.

Please look  at https://github.com/cloudfoundry-community/go-cfclient/pull/37

I will merge to master once the fix will be accepter.

**Comment by jmcarp** [comment]
I'm not sure what I missed--I ran the go-cfclient tests and manually verified that auth with user / client credentials worked. What was the error you ran into?

**Comment by shinji62** [comment]
Well, the PR is for firehose-to-syslog so at least you need to test if there is no breaking changes here.

Anyway, we use GetToken from go-cflient which refer to TokenSource and this was not properly initiated in your case.

Not big deal

**Comment by jmcarp** [comment]
Got it, sorry and thanks for the fix!

**Pull request merged**
