### PR TITLE
Application name Lookup 

### PR DESCRIPTION
**Pull request by shinji62**
This PR is not finish yet.

Added boltdb as backend
Lookup to Cloudcontroller api using go-cfclient
Currently only load app name during startup

Missing : 
Ticker / goroutine to check the CC api every X seconds

I choose boltdb because is lightweight no dependency and easy to use.

There is an issue in gocf-client https://github.com/cloudfoundry-community/go-cfclient/pull/1 I push my Godep dependencies with so should be ok.

### CODE REVIEW

**Comment by shinji62** [comment]
Part of https://github.com/cloudfoundry-community/firehose-to-syslog/issues/8

Should be easy to add more information now, just need to change the caching part.

**Comment by simonjohansson** [comment]
Sweet!

I wonder though if it would be better to fill the cache as we go rather than at startup?

**Comment by shinji62** [comment]
I got the point, will try to implement that.

**Comment by simonjohansson** [comment]
@shinji62 that sounds reasonable!

I will be on holiday for the coming two weeks, feel free to merge yourself when your happy with the implementation. :)

**Comment by shinji62** [comment]
Nice :) I will be in the US for training for two weeks too, but I will try to implement that

**Comment by mrdavidlaing** [comment]
@shinji62 - Thanks for making me aware of this.  

Looking forward to trying out your solution when it is ready.

**Comment by shinji62** [comment]
yes just need a little more time with that.

**Comment by shinji62** [comment]
@mrdavidlaing Please try my branch the application name logic is done.

**Comment by simonjohansson** [comment]
Lovely! Im still on holiday for a week, so again, feel free to merge if working/clean :)

**Comment by mrdavidlaing** [comment]
@shinji62 - I'm attempting to update the logsearch-for-cloudfoundry-boshrelease](https://github.com/logsearch/logsearch-for-cloudfoundry/pull/26), but am getting this error in the compile stage:

```
+ set -x
+ REPO_NAME=github.com/SpringerPE/firehose-to-syslog
+ REPO_DIR=/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog
++ dirname /var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog
+ rm -rf /var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE
++ dirname /var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog
+ mkdir -p /var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE
+ mkdir -p /var/vcap/packages/firehose-to-syslog/bin
++ basename github.com/SpringerPE/firehose-to-syslog
+ cp -a firehose-to-syslog/ /var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog
++ readlink -nf /var/vcap/packages/golang1.4
+ export GOROOT=/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065
+ GOROOT=/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065
+ export GOPATH=/var/vcap/packages/firehose-to-syslog:/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/Godeps/_workspace
+ GOPATH=/var/vcap/packages/firehose-to-syslog:/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/Godeps/_workspace
+ export PATH=/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ PATH=/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ go install github.com/SpringerPE/firehose-to-syslog
../../../packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/main.go:5:2: cannot find package "github.com/cloudfoundry-community/firehose-to-syslog/events" in any of:
	/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065/src/github.com/cloudfoundry-community/firehose-to-syslog/events (from $GOROOT)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/events (from $GOPATH)
	/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/firehose-to-syslog/events
../../../packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/main.go:6:2: cannot find package "github.com/cloudfoundry-community/firehose-to-syslog/firehose" in any of:
	/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065/src/github.com/cloudfoundry-community/firehose-to-syslog/firehose (from $GOROOT)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/firehose (from $GOPATH)
	/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/firehose-to-syslog/firehose
../../../packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/main.go:7:2: cannot find package "github.com/cloudfoundry-community/firehose-to-syslog/logging" in any of:
	/var/vcap/data/packages/golang1.4/f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7.1-1e752140c0093889eea3032e9cab9bdde4a9f065/src/github.com/cloudfoundry-community/firehose-to-syslog/logging (from $GOROOT)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/logging (from $GOPATH)
	/var/vcap/packages/firehose-to-syslog/src/github.com/SpringerPE/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/firehose-to-syslog/logging
```

Any ideas?

**Comment by mrdavidlaing** [comment]
@shinji62 - nevermind; I see the dependancy names have changed from `SpringerPE/firehose-to-syslog`  to `cloudfoundry-community/firehose-to-syslog`

**Comment by mrdavidlaing** [comment]
@shinji62 - ok; now I really am stuck.  Compilating works, but when I try run in the context of my test CF installation, I get the following:

```
root@fe66eaf2-c4b1-4227-b03c-453355ae0663:/var/vcap/packages/firehose-to-syslog/bin# ./firehose-to-syslog --domain=run.54.183.203.97.xip.io --user=admin --password=XXXXXXX --syslog-server=127.0.0.1:5514 --debug --skip-ssl-validation
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45e362]

goroutine 1 [running]:
github.com/cloudfoundry-community/go-cfclient.(*Client).getToken(0xc208056180, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go:180 +0xa22
github.com/cloudfoundry-community/go-cfclient.(*Client).GetToken(0xc208056180, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go:156 +0x44
main.main()
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/main.go:43 +0x496

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

Can you help me debug further please.

I think it might be something to do with the fact that my `cf-domain` is `run.54.183.203.97.xip.io` and/or the fact that I'm using self generated ssl certs

**Comment by mrdavidlaing** [comment]
FWIW, the my CF's environment's URLs are:
```
https://api.run.54.183.203.97.xip.io
https://uaa.run.54.183.203.97.xip.io
wss://doppler.run.54.183.203.97.xip.io
```

**Comment by shinji62** [comment]
Ok let me merge to dev. First

**Comment by shinji62** [comment]
@mrdavidlaing I merge to dev now, the error you got is most likely whn you can t reach you endpoint.
Check the options section on the README, options have been changed

**Pull request merged**
