### PR TITLE
Feature/new docker image

### PR DESCRIPTION
**Pull request by shinji62**
This is a big PR

New Feature : 

* Profiling Options
* Docker in Docker
   Now the Docker Image is build inside Docker and the image is only 7MG
  Exec is built with the static library

Improvement : 
 * Use ffjson instead of std lib
 According to the profiling we decrease the timeconsumed by unmarshalled and so on

### CODE REVIEW

**Comment by simonjohansson** [comment]
Sweet, Ill take a look today.

**Comment by simonjohansson** [comment]
Improvements looks good!

Some issues with the Docker setup though.
* Makefile refers to ./docker/... when it should be ./Docker/...
* Buildscipts in ./Docker needs a chmod +x
* I cannot build on Linux, Docker version 1.7.1, build 786b29d
```
Step 8 : CMD docker build  -t getourneau/firehose-to-syslog /gopath/bin
 ---> Running in 86a3c3aae92e
 ---> 375bf1fbeb96
Removing intermediate container 86a3c3aae92e
Successfully built 375bf1fbeb96
docker: error while loading shared libraries: libdevmapper.so.1.02: cannot open shared object file: No such file or directory
``` 

Have a nice weekend!

**Comment by shinji62** [comment]
HUmm about the docker error can you try to add 
```   -v /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 ``` in build-dev.sh
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):$(which docker)   -v /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02   -ti --name firehose-to-syslog-build-dev cloudfoundry-community/firehose-to-syslog-build-dev ``` 
```

**Comment by shinji62** [comment]
Ok
I try to fix the docker issue too, so please test it.

Thanks

**Comment by simonjohansson** [comment]
@shinji62 it seems our docker setups are vastly different.

After 

```
+[ -f /usr/lib/libudev.so.1 ] && UDEV="-v /usr/lib/libudev.so.1:/usr/lib/libudev.so.1"
+[ -f /usr/lib/libcap.so.2 ] && CAP="-v /usr/lib/libcap.so.2:/usr/lib/libcap.so.2"
 
 pushd $DIR
   docker build -t cloudfoundry-community/firehose-syslog-build ./github/
-  docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):$(which docker) $DEV_MAPPER  -ti --name firehose-syslog-build cloudfoundry-community/firehose-syslog-build
+  docker run -v /var/run/docker.sock:/var/run/docker.sock \
+	 -v $(which docker):$(which docker) \
+	 $DEV_MAPPER \
+	 $UDEV \
+	 $CAP \
+	 -ti --name firehose-syslog-build cloudfoundry-community/firehose-syslog-build
```

I still continue to get errors

```
Step 8 : CMD docker build  -t getourneau/firehose-to-syslog /gopath/bin
 ---> Running in b573180164d5
 ---> b00de66867cc
Removing intermediate container b573180164d5
Successfully built b00de66867cc
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libdevmapper.so.1.02)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libudev.so.1)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /usr/lib/libudev.so.1)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libcap.so.2)
```

How is docker setup on your machine?

**Comment by simonjohansson** [comment]
Also, can we split this PR up into 2 different ones? One for the Docker stuff and one for the  profiling/new json lib stuff?

**Comment by shinji62** [comment]
Wow Ok I i will try to do that :)

**Pull request closed without merging**
