### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by jghiloni**
There were quite a few formatting errors that made the document very hard to read -- especially around client ID/secret creation.

### CODE REVIEW

**Comment by jghiloni** [comment]
Commit 1ae0da3 should not have been included in this -- feel free to reject if necessary and I can re-fix. However, if that commit looks like something you'd be interested in, I can add the necessary unit tests.

**Comment by shinji62** [comment]
Hi, I will cherry pick the readme commit.
I think you merge instead of rebasing your branch.

About the changes you are talking to opt-out base on orgs, I am not really interested in the actual form.

I think you should keep the parameters thought main and not directly calling `os.Getenv` and I think you can optimize using regexp instead of `suffix, prefix and so on ..`


thanks for the readme fix anyway.

**Comment by jghiloni** [comment]
Great, thanks! That was a feature I was working on before I found the `F2S_DISABLE_LOGGING` feature, which did what we needed.

On Jan 30, 2017 23:14, Etourneau Gwenn <notifications@github.com> wrote:

Hi, I will cherry pick the readme commit.
I think you merge instead of rebasing your branch.

About the changes you are talking to opt-out base on orgs, I am not really interested in the actual form.

I think you should keep the parameters thought main and not directly calling os.Getenv and I think you can optimize using regexp instead of suffix, prefix and so on ..

thanks for the readme fix anyway.

**Comment by shinji62** [comment]
I udpdated in 2.5.0 thanks.

**Pull request closed without merging**
