### PR TITLE
Update cfclient

### PR DESCRIPTION
**Pull request by nrxus**
The currently vendored version ignores errors and crashes. This newer
version lets us fail gracefully. This commit does not propagate the
error to preserve backwards compatibility with the API.

Signed-off-by: Matt Cholick mcholick@pivotal.io

### CODE REVIEW

**Comment by shinji62** [comment]
Are you sure your code is compiling ?

Signature of NewClient change in go-cfclient and now return error too, it strange that's you didn't change the main.go code ...

Please can you check ..

**Comment by nrxus** [comment]
Oops, I did not run main.go, only the tests. It is all fixed now.

**Comment by shinji62** [comment]
hummm testing the main.go is at least the minimun :p 

Thanks for the PR

**Comment by shinji62** [comment]
Added to Release 2.2.0

**Pull request merged**
