### PR TITLE
Docker in Docker

### PR DESCRIPTION
**Pull request by shinji62**
Signed-off-by: Etourneau Gwenn <gwenn.etourneau@gmail.com>

### CODE REVIEW

**Comment by simonjohansson** [comment]
Will try to get this to run on my machine, (Arch, Docker version 1.8.1, build d12ea79, 4.1.5-1-ARCH)

**Comment by shinji62** [comment]
Still not running ?

**Comment by simonjohansson** [comment]
Hi @shinji62 , sorry, have not had time to look into it again. 

I will ask someone from my team who runs a normal distro if they can run this.

**Comment by simonjohansson** [comment]
Pah, have not had time to look into this, I will merge for now so you at least can use it :)

**Pull request merged**
