### PR TITLE
Rename "index" field to "job_index"

### LINKED ISSUE #119: Field collision with 'index' keyword in Splunk
'index' field was introduced in 1.7.0.
ref: https://github.com/cloudfoundry-community/firehose-to-syslog/commit/58c09896bec6d17653e2e27e9b050845ac891358

1.7.0+ firehose-to-syslog event messages are annotated with a field name of 'index' which conflicts with Splunk's use of 'index' keyword to specify database indices in search queries.
Can we change the 'index' field name in the AnnotateWithEnveloppeData function to something like 'job_index'?

### PR DESCRIPTION
**Pull request by jhunt**
Fixes #119

### CODE REVIEW

**Comment by shinji62** [comment]
James, again the problem is not the the nozzle but splunk.
Any trouble with syslog and so on.
I don't want to adapt the nozzle for every conflict in every software.

**Comment by jhunt** [comment]
Does the proposed change break any existing functionality in other consumers?  I think seamless out-of-box experience is an important thing to strive for.

**Comment by shinji62** [comment]
Let me check with the logsearch team I will merge this next week. Please wait a little bit.

Thanks

**Comment by jhunt** [comment]
Thanks!

**Pull request merged**
