### PR TITLE
implement reading from loggregator v2 api

### PR DESCRIPTION
**Pull request by MasslessParticle**
Signed-off-by: Travis Patterson <tpatterson@pivotal.io>

### CODE REVIEW

**Comment by shinji62** [comment]
Thanks for the Pr.

**Comment by jtuchscherer** [comment]
It is probably worth noting that this requires the RLP gateway to be deployed, which has been included in cf-deployment 4.5 (https://github.com/cloudfoundry/cf-deployment/releases/tag/v4.5.0)

**Comment by jtuchscherer** [comment]
@shinji62 Do you need something else to be able to pull in this PR? We would be happy to help.

**Comment by shinji62** [comment]
@jtuchscherer No it's fine.  I would try to merge this week.

Sorry for the delay I am a bit busy now.

**Comment by jtuchscherer** [comment]
No rush. Let us know if you need any help or support.

**Comment by shinji62** [comment]
@jtuchscherer 
Test are failing on my CI
```
Failed to compile firehoseclient:

firehoseclient/firehoseclient.go:4:2: cannot find package "code.cloudfoundry.org/go-loggregator" in any of:
	/tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/vendor/code.cloudfoundry.org/go-loggregator (vendor tree)
	/usr/local/go/src/code.cloudfoundry.org/go-loggregator (from $GOROOT)
	/tmp/build/0d1a4794/gopath/src/code.cloudfoundry.org/go-loggregator (from $GOPATH)
firehoseclient/v2adapter.go:5:2: cannot find package "code.cloudfoundry.org/go-loggregator/conversion" in any of:
	/tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/vendor/code.cloudfoundry.org/go-loggregator/conversion (vendor tree)
	/usr/local/go/src/code.cloudfoundry.org/go-loggregator/conversion (from $GOROOT)
	/tmp/build/0d1a4794/gopath/src/code.cloudfoundry.org/go-loggregator/conversion (from $GOPATH)
firehoseclient/v2adapter.go:6:2: cannot find package "code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2" in any of:
	/tmp/build/0d1a4794/gopath/src/github.com/cloudfoundry-community/firehose-to-syslog/vendor/code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2 (vendor tree)
	/usr/local/go/src/code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2 (from $GOROOT)
	/tmp/build/0d1a4794/gopath/src/code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2 (from $GOPATH)

Ginkgo ran 7 suites in 39.766801451s
Test Suite Failed
make: *** [Makefile:6: test] Error 1
```

I guess some vendored dependency are missing.

**Comment by jtuchscherer** [comment]
@shinji62 I created this bug to have the team look into this: https://www.pivotaltracker.com/story/show/164885375
cc/ @MasslessParticle

**Comment by johncornish** [comment]
@shinji62 

I tried a fresh clone of our work and didn't get the error you're seeing, but I did get some strange type errors. I ran `GO111MODULE=on go test ./...` and it worked--not probably the answer you're looking for, but could we have more information about how you're running this?

**Comment by chentom88** [comment]
@shinji62 @jtuchscherer @MasslessParticle 
It was indeed missing dependencies. We added them and opened a new PR:

https://github.com/cloudfoundry-community/firehose-to-syslog/pull/214

**Comment by sba30** [comment]
Any idea when i release will be cut with this change?

**Pull request merged**
